doctrine:
    orm:
        entity_managers:
            default:
                dql:
                    string_functions:
                        MATCH_AGAINST: Sowp\SearchModuleBundle\Doctrine\MatchAgainst