services:
#    upload.example:
#        class: Sowp\UploadBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    sowp_article.attachment_listener:
        class: Sowp\UploadBundle\EventListener\AttachmentSubscriber
        arguments: ["@sowp.upload_bundle.file_uploader"]
        tags:
            - { name: doctrine.event_subscriber }

    sowp.upload_bundle.file_uploader:
        class: Sowp\UploadBundle\Service\FileUploader
        arguments: ['%kernel.root_dir%/../web/uploads/attachments/']