# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

#  gedmo.listener.softdeleteable:
#    class: Gedmo\SoftDeleteable\SoftDeleteableListener
#    tags:
#        - { name: doctrine.event_subscriber, connection: default }
#    calls:
#        - [ setAnnotationReader, [ @annotation_reader ] ]
    news_module.attachment_upload:
        class: Sowp\NewsModuleBundle\EventListener\Doctrine\AttachmentUploadListener
        arguments: ['%sowp_news_module_upload_path%']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }