services:
#    api.example:
#        class: Sowp\ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    api_helper:
        class: Sowp\ApiBundle\Service\ApiHelper
        arguments: ['@jms_serializer']